version: '2'
services:
  db:
    image: postgres:9.4-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    environment:
      - DATABASE_URL=postgresql://db/postgres?user=postgres&password=postgres
      - RACK_ENV=production
    # volumes:
    #   - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
