version: '2'
services:
  db:
    image: postgres:9.4-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    # command: bundle exec rails s -p 3000 -b '0.0.0.0'
    command: bundle exec puma -C config/puma.rb
    environment:
      - DATABASE_URL=jdbc:postgresql://db/postgres?user=postgres&password=postgres
      - RACK_ENV=production
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
