---
# user: www-data
# group: www-data
# pid: tmp/pids/thin.pid
timeout: 30
wait: 30
log: logs/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
# servers: 1
threaded: true
no-epoll: true
address: 0.0.0.0
port: 3000
# daemonize: true
# socket: tmp/sockets/thin.sock
# chdir: /path/to/your/apps/root
# tag: a-name-to-show-up-in-ps aux
